import {
  formatCodigoAtividade,
  type Agendamento,
  type Aluno,
  type Atividade,
  type Curso,
  type Grupo,
  type Habilidade,
  type Turma,
} from "./academic-types";
import {
  SEED_ATLETA_DIGITAL_ATIVIDADES,
  SEED_ATLETA_DIGITAL_GRUPOS,
} from "./atleta-digital-catalog";
import type { AvaliacaoRecord } from "./avaliacoes-types";
import { toUuid } from "./db-mapping";

// ====================================================================
// CURSOS
// ====================================================================
export const SEED_CURSOS: Curso[] = [
  {
    id: "c-mp",
    cod: "MP",
    nome: "ModeloPreca",
    descricao:
      "Curso integrado de Criativo e Pro Player com encerramento em torneio + feira criativa.",
  },
  {
    id: "c-gp",
    cod: "GP",
    nome: "GamePro",
    descricao: "Formação completa para cyber atletas e criadores de conteúdo de games.",
  },
  {
    id: "c-ad",
    cod: "AD",
    nome: "Atleta Digital",
    descricao:
      "Formação de Atleta Digital: Game Play, Design, IA, Ética, Inglês, Posicionamento Digital, Estratégia de Conteúdo, Ferramentas e Fechamento.",
  },
  {
    id: "c-rb",
    cod: "RB",
    nome: "Robótica",
    descricao: "Robótica com Design Thinking, Eletrônica, Modelagem 3D e produção acadêmica.",
  },
];

// ====================================================================
// TURMAS — turmas não têm professor; o professor pertence à atividade.
// ====================================================================
export const SEED_TURMAS: Turma[] = [
  // ----- MP -----
  {
    id: "t-mp-1",
    cursoId: "c-mp",
    nome: "MP_T1",
    cod: "MP_T1",
    data: "2026-02-02",
    horarios: [{ diaSemana: "seg", inicio: "14:00", fim: "15:00" }],
    alunosIds: [
      "al-mp-001-ana-carolina-ramos-da-silva",
      "al-mp-002-antonio-gabriel",
      "al-mp-003-arthur-luis-miranda-lima-de-ca",
      "al-mp-004-heitor-luis-miranda-lima-de-ca",
      "al-mp-005-lukas-kaue-de-sousa-abreu",
      "al-mp-006-maria-cecilia-pereira-da-silva",
      "al-mp-007-maria-helena-lemos-oliveira",
      "al-mp-008-maria-sophia-cabral-freitas",
      "al-mp-009-maria-sophia-dos-santos-rodrig",
      "al-mp-010-mario-aquiles-lacerda-carvalho",
      "al-mp-011-matheus-victor-barbosa-silva",
      "al-mp-012-pedro-felipe-vieira-de-araujo",
      "al-mp-013-ravena-rodrigues-da-silva",
      "al-mp-014-thiago-wallace-lima",
    ],
  },
  {
    id: "t-mp-2",
    cursoId: "c-mp",
    nome: "MP_T2",
    cod: "MP_T2",
    data: "2026-01-23",
    horarios: [{ diaSemana: "sex", inicio: "09:00", fim: "10:00" }],
    alunosIds: [
      "al-mp-015-gustavo-henrique-sousa-rodrigu",
      "al-mp-016-agata-edite-guimaraes-lopes",
      "al-mp-017-islan-kildery-rocha-meneses",
    ],
  },
  {
    id: "t-mp-3",
    cursoId: "c-mp",
    nome: "MP_T3",
    cod: "MP_T3",
    data: "2026-01-23",
    horarios: [{ diaSemana: "sex", inicio: "14:00", fim: "15:00" }],
    alunosIds: [
      "al-mp-018-anna-victoria-de-sousa-santos",
      "al-mp-019-carlos-emanuel-silva-feitosa",
      "al-mp-020-carlos-gabriel-s-j",
      "al-mp-021-elias-ezequiel-da-silva-de-jes",
      "al-mp-022-enzo-gabriel-sousa-de-oliveira",
      "al-mp-023-esdras-emanoel-medeiros-silva",
      "al-mp-024-italo-candido-de-oliveira",
      "al-mp-025-lucas-daniel-dos-santos-silva",
      "al-mp-026-lucas-oliveira-reis",
      "al-mp-027-maria-cecilia-silva-campos",
      "al-mp-028-noah-kalel-mineiro-sousa",
      "al-mp-029-paulo-wanderson-de-araujo",
      "al-mp-030-pedro-felipe-vieira-de-araujo",
      "al-mp-031-thiago-walter-lima-de-almeida",
    ],
  },
  {
    id: "t-mp-4",
    cursoId: "c-mp",
    nome: "MP_T4",
    cod: "MP_T4",
    data: "2026-01-24",
    horarios: [{ diaSemana: "sab", inicio: "07:30", fim: "08:30" }],
    alunosIds: [
      "al-mp-032-ana-beatriz-marques-do-nascime",
      "al-mp-033-ana-beatriz-nunes-barbosa",
      "al-mp-034-camila-chaves-diniz",
      "al-mp-035-david-kaua-da-silva-aguiar",
      "al-mp-036-eduardo-porfirio-alves-de-arau",
      "al-mp-037-eduardo-santos-freitas",
      "al-mp-038-jose-henrique-alves-silva",
      "al-mp-039-marcos-antonio-bezerra-sousa",
      "al-mp-040-marcio-emanuel-pinto-da-silva-",
      "al-mp-041-marcus-vinicius-pinto-da-silva",
      "al-mp-042-maria-cecilia-sousa-vidal",
      "al-mp-043-matheus-dias-de-sousa",
      "al-mp-044-nicollas-riquelme-de-sousa-men",
      "al-mp-045-nicolly-lauranda-de-sousa-mend",
      "al-mp-046-ruan-augusthus-costa-dos-santo",
      "al-mp-047-ruan-matheus-dias-de-sousa",
      "al-mp-048-samuel-yuri-damasceno-araujo",
    ],
  },
  {
    id: "t-mp-5",
    cursoId: "c-mp",
    nome: "MP_T5",
    cod: "MP_T5",
    data: "2026-01-25",
    horarios: [{ diaSemana: "dom", inicio: "10:00", fim: "11:00" }],
    alunosIds: [
      "al-mp-049-adriel-de-sousa-rosa-galvao",
      "al-mp-050-andressa-vitoria-andrade-ferre",
      "al-mp-051-arthur-lima-de-carvalho-silva",
      "al-mp-052-carlos-eduardo-de-lima",
      "al-mp-053-clara-sofia-paes-landim-lopes",
      "al-mp-054-guana-suellem-andrade-morais",
      "al-mp-055-gustavo-barreto",
      "al-mp-056-izaquiel-barreto-lopes",
      "al-mp-057-jose-carlos-madeira-santana-ne",
      "al-mp-058-jose-silva",
      "al-mp-059-kerven-renan-de-oliveira-costa",
      "al-mp-060-luara-maria-regina-aragao",
      "al-mp-061-matheus-rodrigues-soares-da-si",
      "al-mp-062-pedro-misael-alves-miranda",
      "al-mp-063-ruan-augusto",
      "al-mp-064-werick-kauan",
      "al-mp-065-wilker-carvalho-vieira",
    ],
  },
  {
    id: "t-mp-6",
    cursoId: "c-mp",
    nome: "MP_T6",
    cod: "MP_T6",
    data: "2026-03-17",
    horarios: [{ diaSemana: "ter", inicio: "14:00", fim: "15:00" }],
    alunosIds: [
      "al-mp-066-enzo-ravy-do-monte-resende-cam",
      "al-mp-067-fabrinne-emanuelle-dos-santos-",
      "al-mp-068-flavio-anderson-passos-silva",
      "al-mp-069-francisco-kaua-da-silva-reis",
      "al-mp-070-francisco-lucas-gama-da-silva",
      "al-mp-071-francislany-ribeiro-de-abreu",
      "al-mp-072-gabriela-lorrany-de-brandao-co",
      "al-mp-073-iarley-henrique-santos-ferreir",
      "al-mp-074-luis-henrique-da-silva-barros",
      "al-mp-075-maria-helena-pereira-lima-da-s",
      "al-mp-076-saulo-emanuel-oliveira-lopes",
      "al-mp-077-vivian-emanuelly-da-costa-oliv",
    ],
  },
  {
    id: "t-mp-7",
    cursoId: "c-mp",
    nome: "MP_T7",
    cod: "MP_T7",
    data: "2026-03-10",
    horarios: [{ diaSemana: "ter", inicio: "14:00", fim: "15:00" }],
    alunosIds: [
      "al-mp-078-adriely-emilly-rodrigues-de-ba",
      "al-mp-079-fabrinne-emanuelle-dos-santos-",
      "al-mp-080-francisco-kaue-machado-da-silv",
      "al-mp-081-gabriela-lorrany-de-brandao-co",
      "al-mp-082-iara-santos-sousa-vieira",
      "al-mp-083-isaac-gabriel-carvalho-de-sena",
      "al-mp-084-luis-henrique-da-silva-barros",
      "al-mp-085-maria-helena-pereira-lima-da-s",
      "al-mp-086-maria-paula-padua-brandao",
      "al-mp-087-pedro-raniere-silva-lopes",
      "al-mp-088-vitoria-sousa-campos",
      "al-mp-089-william-matheus-lopes-da-silva",
    ],
  },

  // ----- GP -----
  {
    id: "t-gp-2006-1",
    cursoId: "c-gp",
    nome: "GP_T2006-1",
    cod: "GP_T2006-1",
    data: "2026-02-02",
    horarios: [{ diaSemana: "seg", inicio: "14:00", fim: "15:00" }],
    alunosIds: [],
  },
  {
    id: "t-gp-4003-1",
    cursoId: "c-gp",
    nome: "GP_T4003-1",
    cod: "GP_T4003-1",
    data: "2026-02-04",
    horarios: [{ diaSemana: "qua", inicio: "14:00", fim: "15:00" }],
    alunosIds: [],
  },
  {
    id: "t-gp-7003-2",
    cursoId: "c-gp",
    nome: "GP_T7003-2",
    cod: "GP_T7003-2",
    data: "2026-02-07",
    horarios: [{ diaSemana: "sab", inicio: "13:30", fim: "14:30" }],
    alunosIds: [],
  },
  {
    id: "t-gp-7004-1",
    cursoId: "c-gp",
    nome: "GP_T7004-1",
    cod: "GP_T7004-1",
    data: "2026-02-07",
    horarios: [{ diaSemana: "sab", inicio: "13:30", fim: "14:30" }],
    alunosIds: [],
  },
  {
    id: "t-gp-8003-2",
    cursoId: "c-gp",
    nome: "GP_T8003-2",
    cod: "GP_T8003-2",
    data: "2026-02-08",
    horarios: [{ diaSemana: "dom", inicio: "12:30", fim: "13:30" }],
    alunosIds: [],
  },

  // ----- AD -----
  {
    id: "t-ad-1",
    cursoId: "c-ad",
    nome: "AD_T1",
    cod: "AD_T1",
    data: "2026-02-03",
    horarios: [
      { diaSemana: "ter", inicio: "16:30", fim: "17:30" },
      { diaSemana: "qui", inicio: "16:30", fim: "17:30" },
    ],
    alunosIds: [],
  },
  {
    id: "t-ad-2",
    cursoId: "c-ad",
    nome: "AD_T2",
    cod: "AD_T2",
    data: "2026-02-08",
    horarios: [{ diaSemana: "dom", inicio: "15:00", fim: "16:00" }],
    alunosIds: [],
  },
  {
    id: "t-ad-3",
    cursoId: "c-ad",
    nome: "AD_T3",
    cod: "AD_T3",
    data: "2026-02-07",
    horarios: [{ diaSemana: "sab", inicio: "10:00", fim: "11:00" }],
    alunosIds: [],
  },
  {
    id: "t-ad-4",
    cursoId: "c-ad",
    nome: "AD_T4",
    cod: "AD_T4",
    data: "2026-02-07",
    horarios: [{ diaSemana: "sab", inicio: "15:00", fim: "16:00" }],
    alunosIds: [],
  },

  // ----- RB -----
  {
    id: "t-rb-1",
    cursoId: "c-rb",
    nome: "RB_T1",
    cod: "RB_T1",
    data: "2026-02-04",
    horarios: [{ diaSemana: "qua", inicio: "19:00", fim: "20:00" }],
    alunosIds: [],
  },
];

export const SEED_ALUNOS: Aluno[] = [
  {
    id: "al-mp-001-ana-carolina-ramos-da-silva",
    nome: "Ana Carolina Ramos da Silva",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-002-antonio-gabriel",
    nome: "Antônio Gabriel",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-003-arthur-luis-miranda-lima-de-ca",
    nome: "Arthur Luis Miranda Lima de Carvalho",
    contato: "(86) 9 8818-4522",
    cpf: "780.813.138-5",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-004-heitor-luis-miranda-lima-de-ca",
    nome: "Heitor Luis Miranda Lima de Carvalho",
    contato: "",
    cpf: "078.081.443-63",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-005-lukas-kaue-de-sousa-abreu",
    nome: "Lukas Kauê de Sousa Abreu",
    contato: "(86) 9 992*",
    cpf: "750.904.836-2",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-006-maria-cecilia-pereira-da-silva",
    nome: "Maria Cecilia Pereira da Silva",
    contato: "(86) 9 9922-1582",
    cpf: "306.466.958-61",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-007-maria-helena-lemos-oliveira",
    nome: "Maria Helena Lemos Oliveira",
    contato: "",
    cpf: "109.469.937-0",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-008-maria-sophia-cabral-freitas",
    nome: "Maria Sophia Cabral Freitas",
    contato: "(86) 9 8896-1456",
    cpf: "717.958.132-1",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-009-maria-sophia-dos-santos-rodrig",
    nome: "Maria Sophia dos Santos Rodrigues",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-010-mario-aquiles-lacerda-carvalho",
    nome: "Mario Aquiles Lacerda Carvalho",
    contato: "(86) 9 8884-2638",
    cpf: "555.505.235-9",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-011-matheus-victor-barbosa-silva",
    nome: "Matheus Victor Barbosa Silva",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-012-pedro-felipe-vieira-de-araujo",
    nome: "Pedro Felipe Vieira de Araujo",
    contato: "",
    cpf: "072.572.273-81",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-013-ravena-rodrigues-da-silva",
    nome: "Ravena Rodrigues da Silva",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-014-thiago-wallace-lima",
    nome: "Thiago Wallace Lima",
    contato: "",
    cpf: "081.277.403-57",
    cursoId: "c-mp",
    turmaId: "t-mp-1",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-015-gustavo-henrique-sousa-rodrigu",
    nome: "Gustavo Henrique Sousa Rodrigues",
    contato: "(86) 9 9436-5511",
    cpf: "742.570.738-1",
    cursoId: "c-mp",
    turmaId: "t-mp-2",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-016-agata-edite-guimaraes-lopes",
    nome: "Agata Edite Guimarães Lopes",
    contato: "(86) 9 9807-2370",
    cpf: "511.264.918-61",
    cursoId: "c-mp",
    turmaId: "t-mp-2",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-017-islan-kildery-rocha-meneses",
    nome: "Islan Kildery Rocha Meneses",
    contato: "(86) 9 9421-3788",
    cpf: "934.594.732-9",
    cursoId: "c-mp",
    turmaId: "t-mp-2",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-018-anna-victoria-de-sousa-santos",
    nome: "Anna Victória de Sousa Santos",
    contato: "",
    cpf: "065.751.393-88",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-019-carlos-emanuel-silva-feitosa",
    nome: "Carlos Emanuel Silva Feitosa",
    contato: "",
    cpf: "066.011.003-23",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-p-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-020-carlos-gabriel-s-j",
    nome: "Carlos Gabriel S.J",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-p-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-021-elias-ezequiel-da-silva-de-jes",
    nome: "Elias Ezequiel da Silva de Jesus",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-p-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-022-enzo-gabriel-sousa-de-oliveira",
    nome: "Enzo Gabriel Sousa de Oliveira",
    contato: "",
    cpf: "123.275.253-30",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-023-esdras-emanoel-medeiros-silva",
    nome: "Esdras Emanoel Medeiros Silva",
    contato: "",
    cpf: "076.784.783-05",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-p-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-024-italo-candido-de-oliveira",
    nome: "Ítalo Cândido de Oliveira",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-025-lucas-daniel-dos-santos-silva",
    nome: "Lucas Daniel dos Santos Silva",
    contato: "",
    cpf: "073.705.133-78",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-p-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-026-lucas-oliveira-reis",
    nome: "Lucas Oliveira Reis",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-p-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-027-maria-cecilia-silva-campos",
    nome: "Maria Cecilia Silva Campos",
    contato: "",
    cpf: "070.424.413-62",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-p-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-028-noah-kalel-mineiro-sousa",
    nome: "Noah Kalel Mineiro Sousa",
    contato: "",
    cpf: "087.695.703-37*",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-029-paulo-wanderson-de-araujo",
    nome: "Paulo Wanderson de Araujo",
    contato: "",
    cpf: "101.147.533-26",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-030-pedro-felipe-vieira-de-araujo",
    nome: "Pedro Felipe Vieira de Araújo",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-031-thiago-walter-lima-de-almeida",
    nome: "Thiago Walter Lima de Almeida",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-3",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-p-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-032-ana-beatriz-marques-do-nascime",
    nome: "Ana Beatriz Marques do Nascimento",
    contato: "(86) 9 8861-53288",
    cpf: "093.500.313-45",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-033-ana-beatriz-nunes-barbosa",
    nome: "Ana Beatriz Nunes Barbosa",
    contato: "",
    cpf: "077.115.713-48",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-034-camila-chaves-diniz",
    nome: "Camila Chaves Diniz",
    contato: "",
    cpf: "627.592.523-02",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-035-david-kaua-da-silva-aguiar",
    nome: "David Kauã da Silva Aguiar",
    contato: "(86) 9 8833-3521",
    cpf: "074.749.303-07",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-036-eduardo-porfirio-alves-de-arau",
    nome: "Eduardo Porfírio Alves de Araújo",
    contato: "(86) 9 8107-3018",
    cpf: "083.867.373-28",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-037-eduardo-santos-freitas",
    nome: "Eduardo Santos Freitas",
    contato: "(86) 9  8830-9431",
    cpf: "068.608.923-58",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-038-jose-henrique-alves-silva",
    nome: "José Henrique Alves Silva",
    contato: "",
    cpf: "074.119.463-54",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-039-marcos-antonio-bezerra-sousa",
    nome: "Marcos Antonio Bezerra Sousa",
    contato: "(86) 9 9988-2165  (86) 9 9975-4992",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-040-marcio-emanuel-pinto-da-silva-",
    nome: "Márcio Emanuel Pinto da Silva Monteiro",
    contato: "(86) 9 8904-2385 (86) 9 8839-7899",
    cpf: "081.565.313-10",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-041-marcus-vinicius-pinto-da-silva",
    nome: "Marcus Vinicius Pinto da Silva Monteiro",
    contato: "",
    cpf: "081.565.203-86",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-042-maria-cecilia-sousa-vidal",
    nome: "Maria Cecília Sousa Vidal",
    contato: "",
    cpf: "065.796.083-74",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-043-matheus-dias-de-sousa",
    nome: "Matheus Dias de Sousa",
    contato: "",
    cpf: "628.860.473-92",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-044-nicollas-riquelme-de-sousa-men",
    nome: "Nicollas Riquelme de Sousa Mendes",
    contato: "",
    cpf: "109.140.893-90",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-045-nicolly-lauranda-de-sousa-mend",
    nome: "Nicolly Lauranda de Sousa Mendes",
    contato: "",
    cpf: "074.236.523.93",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-046-ruan-augusthus-costa-dos-santo",
    nome: "Ruan Augusthus Costa dos Santos",
    contato: "",
    cpf: "074.236.523.93",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-047-ruan-matheus-dias-de-sousa",
    nome: "Ruan Matheus Dias de Sousa",
    contato: "(86) 9 9484-4606",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-048-samuel-yuri-damasceno-araujo",
    nome: "Samuel Yuri Damasceno Araújo",
    contato: "(86) 9 9816-6567",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-4",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-049-adriel-de-sousa-rosa-galvao",
    nome: "Adriel de Sousa Rosa Galvão",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-050-andressa-vitoria-andrade-ferre",
    nome: "Andressa Vitória Andrade Ferreira",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-051-arthur-lima-de-carvalho-silva",
    nome: "Arthur Lima de Carvalho Silva",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-052-carlos-eduardo-de-lima",
    nome: "Carlos Eduardo de Lima",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-06", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-053-clara-sofia-paes-landim-lopes",
    nome: "Clara Sofia Paes Landim Lopes",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-06", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-054-guana-suellem-andrade-morais",
    nome: "Guana Suellem Andrade Morais",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-055-gustavo-barreto",
    nome: "Gustavo Barreto",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-056-izaquiel-barreto-lopes",
    nome: "Izaquiel Barreto Lopes",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-057-jose-carlos-madeira-santana-ne",
    nome: "José Carlos Madeira Santana Neto",
    contato: "",
    cpf: "733.875.383-*",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-058-jose-silva",
    nome: "José Silva",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-059-kerven-renan-de-oliveira-costa",
    nome: "Kerven Renan de Oliveira Costa",
    contato: "(86) 9 9463-0424",
    cpf: "101.058.183-05",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-060-luara-maria-regina-aragao",
    nome: "Luara Maria Regina Aragão",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-061-matheus-rodrigues-soares-da-si",
    nome: "Matheus Rodrigues Soares da Silva",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-062-pedro-misael-alves-miranda",
    nome: "Pedro Misael Alves Miranda",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: false },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-063-ruan-augusto",
    nome: "Ruan Augusto",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-064-werick-kauan",
    nome: "Werick Kauan",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: false },
      { atividadeId: "at-mp-p-aula-01", presente: false },
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-p-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-p-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
      { atividadeId: "at-mp-p-aula-04", presente: false },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-06", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-065-wilker-carvalho-vieira",
    nome: "Wilker Carvalho Vieira",
    contato: "(86) 9 9456-9169",
    cpf: "093.733.434-36*",
    cursoId: "c-mp",
    turmaId: "t-mp-5",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-01", presente: true },
      { atividadeId: "at-mp-p-aula-01", presente: true },
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-p-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-p-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
      { atividadeId: "at-mp-p-aula-04", presente: true },
      { atividadeId: "at-mp-c-aula-05", presente: true },
      { atividadeId: "at-mp-c-aula-06", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-066-enzo-ravy-do-monte-resende-cam",
    nome: "ENZO RAVY DO MONTE RESENDE CAMILO",
    contato: "(86) 9 9940-3121",
    cpf: "077.362.853-30",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-067-fabrinne-emanuelle-dos-santos-",
    nome: "FABRINNE EMANUELLE DOS SANTOS COSTA",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-068-flavio-anderson-passos-silva",
    nome: "FLAVIO ANDERSON PASSOS SILVA",
    contato: "(86) 9 9932-2830 (86) 9 9461-9635",
    cpf: "103.906.073-04",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-069-francisco-kaua-da-silva-reis",
    nome: "FRANCISCO KAUA DA SILVA REIS",
    contato: "(86) 9 9461-9635",
    cpf: "099.360.073-52",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-070-francisco-lucas-gama-da-silva",
    nome: "FRANCISCO LUCAS GAMA DA SILVA",
    contato: "(86) 9 9519-0062",
    cpf: "079.732.423-25",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-071-francislany-ribeiro-de-abreu",
    nome: "FRANCISLANY RIBEIRO DE ABREU",
    contato: "(86) 9 9433-3092",
    cpf: "096.810.473-89",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-072-gabriela-lorrany-de-brandao-co",
    nome: "GABRIELA LORRANY DE BRANDÃO COSTA",
    contato: "(86) 9 8553-1314",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-073-iarley-henrique-santos-ferreir",
    nome: "IARLEY HENRIQUE SANTOS FERREIRA",
    contato: "(86) 9 9515-8523",
    cpf: "109.262.723-57",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-074-luis-henrique-da-silva-barros",
    nome: "LUIS HENRIQUE DA SILVA BARROS",
    contato: "(86) 9 8808-1731",
    cpf: "124.018.433-61",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-075-maria-helena-pereira-lima-da-s",
    nome: "MARIA HELENA PEREIRA LIMA DA SILVA",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-076-saulo-emanuel-oliveira-lopes",
    nome: "SAULO EMANUEL OLIVEIRA LOPES",
    contato: "(86) 9 9930-0144",
    cpf: "084.228.403-67",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-077-vivian-emanuelly-da-costa-oliv",
    nome: "VIVIAN EMANUELLY DA COSTA OLIVEIRA",
    contato: "(86) 9 8829-9107",
    cpf: "102.583.033-44",
    cursoId: "c-mp",
    turmaId: "t-mp-6",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-078-adriely-emilly-rodrigues-de-ba",
    nome: "Adriely Emilly Rodrigues de Barros",
    contato: "(86) 9 8144-4896",
    cpf: "110.739.913-00",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-079-fabrinne-emanuelle-dos-santos-",
    nome: "Fabrinne Emanuelle dos Santos Costa",
    contato: "(86) 9 9816-5385",
    cpf: "080.344.203-36",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-080-francisco-kaue-machado-da-silv",
    nome: "Francisco Kaue Machado da Silva",
    contato: "(86) 9 9519-0062",
    cpf: "123.215.883-65",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-081-gabriela-lorrany-de-brandao-co",
    nome: "Gabriela Lorrany de Brandão Costa",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-082-iara-santos-sousa-vieira",
    nome: "Iara Santos Sousa Vieira",
    contato: "(86) 9 9407-0810",
    cpf: "120.875.033-03",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-083-isaac-gabriel-carvalho-de-sena",
    nome: "Isaac Gabriel Carvalho de Sena",
    contato: "(86) 9 9859-0026",
    cpf: "085.875.433-93",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-084-luis-henrique-da-silva-barros",
    nome: "Luis Henrique da Silva Barros",
    contato: "",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-085-maria-helena-pereira-lima-da-s",
    nome: "Maria Helena Pereira Lima da Silva",
    contato: "(86) 9 9475-9167",
    cpf: "033.647.393-15",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-086-maria-paula-padua-brandao",
    nome: "Maria Paula Padua Brandão",
    contato: "(86) 9 8868-0311",
    cpf: "083.772.263-24",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: false },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-087-pedro-raniere-silva-lopes",
    nome: "Pedro Raniere Silva Lopes",
    contato: "(86) 9 9809-7298",
    cpf: "108.754.443-26",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-088-vitoria-sousa-campos",
    nome: "Vitoria Sousa Campos",
    contato: "(86) 9 9934-8290",
    cpf: "101.539.353-59",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: false },
      { atividadeId: "at-mp-c-aula-04", presente: true },
    ],
    trabalhos: [],
  },
  {
    id: "al-mp-089-william-matheus-lopes-da-silva",
    nome: "William Matheus Lopes da Silva Pires",
    contato: "(86) 9 9823-7052",
    cpf: "",
    cursoId: "c-mp",
    turmaId: "t-mp-7",
    habilidadeIds: [],
    aulas: [
      { atividadeId: "at-mp-c-aula-02", presente: true },
      { atividadeId: "at-mp-c-aula-03", presente: true },
      { atividadeId: "at-mp-c-aula-04", presente: false },
    ],
    trabalhos: [],
  },
];

export const SEED_HABILIDADES: Habilidade[] = [
  {
    id: "h-com-01",
    sigla: "COM-01",
    descricao: "Comunicação clara: capacidade de expressar ideias de forma objetiva.",
    grupo: "Socioemocional",
  },
  {
    id: "h-cri-02",
    sigla: "CRI-02",
    descricao: "Criatividade aplicada: gerar soluções originais.",
    grupo: "Cognitivo",
  },
  {
    id: "h-col-03",
    sigla: "COL-03",
    descricao: "Colaboração em equipe: trabalhar coletivamente.",
    grupo: "Socioemocional",
  },
  {
    id: "h-tec-04",
    sigla: "TEC-04",
    descricao: "Domínio técnico de ferramentas digitais.",
    grupo: "Técnico",
  },
];

// ====================================================================
// GRUPOS (Módulos) por curso.
// O `cod` compõe o código da atividade: <CURSO_COD><GRUPO_COD><NN>.
// ====================================================================
// SEED_GRUPOS é indexado por *múltiplas* formas de identificar o curso:
//  - curso.cod ("MP", "GP", "AD", "RB") — canônico, estável e imutável
//  - seed id textual ("c-mp", "c-gp", ...) — compat com código legado
//  - toUuid(seed-id) — compat para cursos seedados via cursosStore
//
// A motivação: o curso no banco pode ter sido criado com um UUID arbitrário
// (ex.: criação manual via UI antes do toUuid existir), então chavear por
// UUID determinístico não é confiável. O `cod` é a única chave garantida
// a bater, então idealmente use-o nos consumidores.
const SEED_GRUPOS_BY_COD: Record<string, Grupo[]> = {
  MP: [
    { cod: "C", nome: "Criativo" },
    { cod: "P", nome: "Pro-Player" },
    { cod: "EV", nome: "Evento" },
  ],
  GP: [
    { cod: "CA", nome: "Canva e Adobe Express" },
    { cod: "FG", nome: "Fundamentos do Game" },
    { cod: "PA", nome: "Pacote Adobe" },
    { cod: "PP", nome: "Pro Player" },
    { cod: "ET", nome: "Estratégias e táticas" },
    { cod: "CH", nome: "Conversação Hard" },
    { cod: "P2", nome: "Pro Player 2" },
    { cod: "IN", nome: "Inglês para Cyber Atletas" },
  ],
  AD: SEED_ATLETA_DIGITAL_GRUPOS,
  RB: [
    { cod: "MD", nome: "Metodologia de Design" },
    { cod: "EP", nome: "Eletrônica e Prototipagem" },
    { cod: "3D", nome: "Modelagem 3D e Fabricação" },
    { cod: "AC", nome: "Artigo Científico e Produção Acadêmica" },
  ],
};

// Mapa cod → seed-id (usado para manter as chaves legadas funcionando).
const COD_TO_SEED_ID: Record<string, string> = {
  MP: "c-mp",
  GP: "c-gp",
  AD: "c-ad",
  RB: "c-rb",
};

export const SEED_GRUPOS: Record<string, Grupo[]> = Object.fromEntries(
  Object.entries(SEED_GRUPOS_BY_COD).flatMap(([cod, grupos]) => {
    const seedId = COD_TO_SEED_ID[cod];
    return [
      [cod, grupos],
      ...(seedId ? [[seedId, grupos] as const, [toUuid(seedId), grupos] as const] : []),
    ];
  }),
);

/**
 * Retorna os grupos/módulos de um curso. Tenta `curso.cod` primeiro (chave
 * canônica), cai para `curso.id` como fallback. Sempre prefira este helper
 * ao acesso direto em SEED_GRUPOS[curso.id], que falha se o curso tiver
 * sido criado com UUID não determinístico.
 */
export function getGruposDoCurso(curso: { id: string; cod: string } | null | undefined): Grupo[] {
  if (!curso) return [];
  return SEED_GRUPOS[curso.cod] ?? SEED_GRUPOS[curso.id] ?? [];
}

// ====================================================================
// ATIVIDADES — catálogo de Aulas (tipo 0) e Tarefas (tipo 1) por curso.
// Códigos no formato <CURSO_COD><GRUPO_COD><NN> (ex.: GPCA01, MPCR01).
// Professor não é definido aqui — é atribuído ao agendar.
// ====================================================================

function mkAula(
  cursoId: string,
  cursoCod: string,
  grupoCod: string,
  seq: number,
  nome: string,
  conteudo: string,
  habilidadeIds: string[] = [],
): Atividade {
  return {
    id: `at-${cursoCod.toLowerCase()}-${grupoCod.toLowerCase()}-aula-${String(seq).padStart(2, "0")}`,
    tipo: 0,
    nome,
    codigo: formatCodigoAtividade(cursoCod, grupoCod, seq),
    cursoId,
    grupo: grupoCod,
    descricao: conteudo,
    objetivoResultados: `Ao final, o aluno deve compreender: ${nome}.`,
    prazo: "2026-12-31",
    criadoPor: "Admin",
    professor: "",
    habilidadeIds,
    descricaoConteudo: conteudo,
    sugestoesPais: "Reforçar o conteúdo em casa com perguntas abertas.",
  };
}

export const SEED_ATIVIDADES: Atividade[] = [
  // ====================================================================
  // MP — ModeloPreca (12 aulas: C=6, P=5, EV=1)
  // ====================================================================
  mkAula(
    "c-mp",
    "MP",
    "C",
    1,
    "Introdução ao Design e Branding para Games",
    "Introdução ao Design e Branding para Games.",
  ),
  mkAula(
    "c-mp",
    "MP",
    "C",
    2,
    "Ferramentas Grátis (Canva, Photoshop)",
    "Visão geral de ferramentas gratuitas: Canva e Photoshop.",
  ),
  mkAula(
    "c-mp",
    "MP",
    "C",
    3,
    "Identidade Visual e Paleta para Streamers",
    "Construção de identidade visual e paleta de cores para streamers.",
  ),
  mkAula(
    "c-mp",
    "MP",
    "C",
    4,
    "Elementos Gráficos: Logos, Banners, e Sobreposições",
    "Criação de logos, banners e sobreposições (overlays).",
  ),
  mkAula(
    "c-mp",
    "MP",
    "C",
    5,
    "Branding Pessoal: Aplicação para Streamers e YouTubers",
    "Branding pessoal aplicado a streamers e YouTubers.",
  ),
  mkAula("c-mp", "MP", "C", 6, "Criação de Portifólio", "Montagem de portfólio criativo do aluno."),

  mkAula("c-mp", "MP", "P", 1, "Introdução ao Mundo Pro Player", "Introdução ao mundo Pro Player."),
  mkAula(
    "c-mp",
    "MP",
    "P",
    2,
    "Mecânicas Avançadas (Aim, Movimentação)",
    "Mecânicas avançadas: aim e movimentação.",
  ),
  mkAula(
    "c-mp",
    "MP",
    "P",
    3,
    "Estratégia e Análise de Jogo (VODs)",
    "Estratégia e análise de jogo a partir de VODs.",
  ),
  mkAula(
    "c-mp",
    "MP",
    "P",
    4,
    "Psicologia Competitiva (Mindset, Tilting)",
    "Psicologia competitiva: mindset e controle de tilt.",
  ),
  mkAula(
    "c-mp",
    "MP",
    "P",
    5,
    "Comunicação, Callouts e Treinamento em Grupo",
    "Comunicação, callouts e treinamento em grupo.",
  ),

  mkAula(
    "c-mp",
    "MP",
    "EV",
    1,
    "Torneio entre alunos + Feira Criativa",
    "Encerramento: torneio entre alunos + feira criativa.",
  ),

  // ====================================================================
  // GP — GamePro (48 aulas em 8 módulos)
  // ====================================================================
  // CA — Canva e Adobe Express
  mkAula(
    "c-gp",
    "GP",
    "CA",
    1,
    "Visão geral do design gráfico",
    "Visão geral do design gráfico aplicada ao mundo dos games.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "CA",
    2,
    "Ferramentas de apoio ao designer",
    "Ferramentas de apoio ao designer: paletas, fontes, mockups.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "CA",
    3,
    "Inteligências Artificiais no Design",
    "Uso de IAs no fluxo de criação visual.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "CA",
    4,
    "Canva do básico ao avançado",
    "Canva: do básico ao avançado, com foco em peças para games.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "CA",
    5,
    "Adobe express do básico ao avançado",
    "Adobe Express: edição rápida e templates.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "CA",
    6,
    "Revisão de conteúdo e prova final",
    "Revisão geral do módulo e prova final.",
  ),
  // FG — Fundamentos do Game
  mkAula(
    "c-gp",
    "GP",
    "FG",
    1,
    "Visão geral e conceitos básicos sobre o game",
    "Visão geral e conceitos básicos sobre o game.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "FG",
    2,
    "Classes e subclasses de cada personagem",
    "Classes e subclasses de cada personagem.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "FG",
    3,
    "Melhor uso de cada skill",
    "Melhor uso de cada skill em diferentes cenários.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "FG",
    4,
    "Armas/skill e utilitários",
    "Armas, skills e utilitários do jogo.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "FG",
    5,
    "Função de cada classe",
    "Função de cada classe na composição do time.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "FG",
    6,
    "Conhecendo os mapas",
    "Conhecendo os mapas: callouts, rotações e pontos-chave.",
  ),
  // PA — Pacote Adobe
  mkAula(
    "c-gp",
    "GP",
    "PA",
    1,
    "Ferramentas e layout Adobe",
    "Visão geral das ferramentas e layout do Pacote Adobe.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "PA",
    2,
    "Photoshop do básico ao avançado",
    "Photoshop: do básico ao avançado.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "PA",
    3,
    "Illustrator do básico ao avançado",
    "Illustrator: do básico ao avançado.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "PA",
    4,
    "PREMIER do básico ao avançado",
    "Premiere: do básico ao avançado.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "PA",
    5,
    "AFTER EFFECTS do básico ao avançado",
    "After Effects: do básico ao avançado.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "PA",
    6,
    "Criação de Highlights - After + Premiere",
    "Criação de Highlights combinando After Effects e Premiere.",
  ),
  // PP — Pro Player
  mkAula(
    "c-gp",
    "GP",
    "PP",
    1,
    "Conceito básico de movimentação",
    "Conceito básico de movimentação.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "PP",
    2,
    "Técnicas de movimentação avançadas",
    "Técnicas de movimentação avançadas.",
  ),
  mkAula("c-gp", "GP", "PP", 3, "Usando o mapa a seu favor", "Como usar o mapa a seu favor."),
  mkAula("c-gp", "GP", "PP", 4, "Técnicas de tiro", "Técnicas de tiro."),
  mkAula(
    "c-gp",
    "GP",
    "PP",
    5,
    "Movimentação e disparo simultâneos",
    "Movimentação e disparo simultâneos.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "PP",
    6,
    "Competição, aplicando técnicas",
    "Competição: aplicando todas as técnicas em situação real.",
  ),
  // ET — Estratégias e táticas
  mkAula("c-gp", "GP", "ET", 1, "Estrategias competitivas", "Estratégias competitivas para times."),
  mkAula(
    "c-gp",
    "GP",
    "ET",
    2,
    "Análise de partidas",
    "Análise de partidas próprias e de profissionais.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "ET",
    3,
    "Respostas táticas",
    "Respostas táticas a diferentes composições adversárias.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "ET",
    4,
    "Ritmo de jogo",
    "Ritmo de jogo: quando pressionar e quando recuar.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "ET",
    5,
    "Análise comportamental",
    "Análise comportamental de adversários e do próprio time.",
  ),
  mkAula("c-gp", "GP", "ET", 6, "Prova final", "Prova final do módulo."),
  // CH — Conversação Hard
  mkAula(
    "c-gp",
    "GP",
    "CH",
    1,
    "Linguagem formal",
    "Linguagem formal aplicada a entrevistas e patrocinadores.",
  ),
  mkAula(
    "c-gp",
    "GP",
    "CH",
    2,
    "Expressões cotidianas",
    "Expressões cotidianas em ambiente competitivo.",
  ),
  mkAula("c-gp", "GP", "CH", 3, "Conversação 2", "Conversação avançada — nível 2."),
  mkAula(
    "c-gp",
    "GP",
    "CH",
    4,
    "Feedforward",
    "Feedforward: comunicar antecipadamente o que se espera.",
  ),
  mkAula("c-gp", "GP", "CH", 5, "Gameplay", "Comunicação durante o gameplay."),
  mkAula("c-gp", "GP", "CH", 6, "Prova prática", "Prova prática do módulo."),
  // P2 — Pro Player 2
  mkAula("c-gp", "GP", "P2", 1, "Rotações", "Rotações entre posições e áreas do mapa."),
  mkAula("c-gp", "GP", "P2", 2, "Jogadas reativas", "Jogadas reativas: ler e responder."),
  mkAula("c-gp", "GP", "P2", 3, "Jogadas de início", "Jogadas de início de round/partida."),
  mkAula("c-gp", "GP", "P2", 4, "Tempo de skills", "Gerenciamento de tempo de skills e cooldowns."),
  mkAula("c-gp", "GP", "P2", 5, "Aplicação prática 1", "Aplicação prática — parte 1."),
  mkAula("c-gp", "GP", "P2", 6, "Aplicação prática 2", "Aplicação prática — parte 2."),
  // IN — Inglês para Cyber Atletas
  mkAula("c-gp", "GP", "IN", 1, "Termos usados nos games", "Termos em inglês usados nos games."),
  mkAula("c-gp", "GP", "IN", 2, "Indução e dedução", "Indução e dedução em conversas técnicas."),
  mkAula(
    "c-gp",
    "GP",
    "IN",
    3,
    "Simplificando Frases",
    "Simplificando frases para comunicação rápida.",
  ),
  mkAula("c-gp", "GP", "IN", 4, "Comunicação competitiva", "Comunicação competitiva em inglês."),
  mkAula("c-gp", "GP", "IN", 5, "Conversação 1", "Conversação — nível 1."),
  mkAula("c-gp", "GP", "IN", 6, "Prova prática", "Prova prática do módulo."),

  // ====================================================================
  // AD - Atleta Digital (98 aulas em 9 módulos)
  // Catálogo completo gerado a partir dos arquivos AD*.json fornecidos.
  // ====================================================================
  ...SEED_ATLETA_DIGITAL_ATIVIDADES,

  // ====================================================================
  // RB — Robótica (20 aulas em 4 módulos: MD=5, EP=7, 3D=5, AC=3)
  // ====================================================================
  // MD — Metodologia de Design
  mkAula(
    "c-rb",
    "RB",
    "MD",
    1,
    "Conhecendo o curso + Design Thinking",
    "Apresentação do curso e introdução ao Design Thinking.",
  ),
  mkAula("c-rb", "RB", "MD", 2, "Definição do Problema", "Definição do problema."),
  mkAula("c-rb", "RB", "MD", 3, "Dados, Mercado e Hipótese", "Dados, mercado e hipótese."),
  mkAula("c-rb", "RB", "MD", 4, "Da Ideia à Decisão", "Da ideia à decisão."),
  mkAula(
    "c-rb",
    "RB",
    "MD",
    5,
    "IA com Propósito: Limites e Ética na Prática",
    "IA com propósito: limites e ética na prática.",
  ),
  // EP — Eletrônica e Prototipagem
  mkAula(
    "c-rb",
    "RB",
    "EP",
    1,
    "Fundamentos de eletrônica no projeto real",
    "Fundamentos de eletrônica aplicados em projeto real.",
  ),
  mkAula(
    "c-rb",
    "RB",
    "EP",
    2,
    "Circuitos Integrados + IA (CI 555)",
    "Circuitos integrados + IA — CI 555.",
  ),
  mkAula("c-rb", "RB", "EP", 3, "Introdução ao Arduino + IA", "Introdução ao Arduino + IA."),
  mkAula(
    "c-rb",
    "RB",
    "EP",
    4,
    "Comunicação e Interfaces do Arduino + IA",
    "Comunicação e interfaces do Arduino + IA.",
  ),
  mkAula("c-rb", "RB", "EP", 5, "Sensores no Arduino + IA", "Sensores no Arduino + IA."),
  mkAula(
    "c-rb",
    "RB",
    "EP",
    6,
    "Controle de Potência, Atuadores e Drivers + IA",
    "Controle de potência, atuadores e drivers + IA.",
  ),
  mkAula(
    "c-rb",
    "RB",
    "EP",
    7,
    "Eletrônica do Braço Robótico — Parte 1",
    "Eletrônica do braço robótico — parte 1.",
  ),
  // 3D — Modelagem 3D e Fabricação
  mkAula(
    "c-rb",
    "RB",
    "3D",
    1,
    "Introdução à Modelagem 3D — Parte 1",
    "Introdução à modelagem 3D — parte 1.",
  ),
  mkAula(
    "c-rb",
    "RB",
    "3D",
    2,
    "Modelagem 3D — Parte 2 (projeto autoral)",
    "Modelagem 3D — parte 2 (projeto autoral).",
  ),
  mkAula(
    "c-rb",
    "RB",
    "3D",
    3,
    "Modelagem 3D — Parte 3 (finalização + STL)",
    "Modelagem 3D — parte 3 (finalização + STL).",
  ),
  mkAula(
    "c-rb",
    "RB",
    "3D",
    4,
    "Operação e manutenção de impressoras 3D",
    "Operação e manutenção de impressoras 3D.",
  ),
  mkAula(
    "c-rb",
    "RB",
    "3D",
    5,
    "Montagem e integração do Braço Robótico",
    "Montagem e integração do braço robótico.",
  ),
  // AC — Artigo Científico
  mkAula(
    "c-rb",
    "RB",
    "AC",
    1,
    "Introdução à Escrita Científica",
    "Introdução à escrita científica.",
  ),
  mkAula(
    "c-rb",
    "RB",
    "AC",
    2,
    "Construindo o Artigo — Estrutura, Revisão e Normas",
    "Construindo o artigo — estrutura, conteúdo, revisão, formatação e normas técnicas.",
  ),
  mkAula(
    "c-rb",
    "RB",
    "AC",
    3,
    "Submissão: Feiras, Eventos e Revistas",
    "Submissão: feiras, eventos e revistas.",
  ),
];

export const SEED_AGENDAMENTOS: Agendamento[] = [];

// ====================================================================
// FORMULÁRIOS (templates do sistema)
// ====================================================================
// Templates mínimos garantidos no banco — qualquer aula passa a ter os
// dois formulários básicos disponíveis (relatório do professor e
// autoavaliação do aluno) sem precisar criar manualmente.
export interface SeedFormulario {
  slug: string;
  nome: string;
  descricao: string | null;
  destinatario: "professor" | "aluno";
  estrutura: Record<string, unknown>;
  isSystem: boolean;
}

export const SEED_FORMULARIOS: SeedFormulario[] = [
  {
    slug: "relatorio_professor",
    nome: "Relatório do Professor",
    descricao:
      "Registro pós-aula do professor: chamada, engajamento, cumprimento do plano e observações.",
    destinatario: "professor",
    estrutura: {
      blocos: [
        {
          titulo: "Chamada",
          descricao: "Registre a presença dos alunos nesta aula.",
          perguntas: [
            {
              id: "chamada_presentes",
              tipo: "texto_longo",
              label: "Alunos presentes",
              descricao: "Liste os alunos presentes (preenchido automaticamente pelo sistema).",
              obrigatorio: false,
            },
          ],
        },
        {
          titulo: "Avaliação da Aula",
          descricao: "Como foi o andamento da aula?",
          perguntas: [
            {
              id: "engajamento_turma",
              tipo: "escala_1_5",
              label: "Engajamento da turma",
              descricao: "Como você avalia o envolvimento e participação dos alunos?",
              obrigatorio: true,
            },
            {
              id: "cumprimento_plano",
              tipo: "escala_1_5",
              label: "Cumprimento do plano de aula",
              descricao: "O conteúdo planejado foi aplicado conforme o esperado?",
              obrigatorio: true,
            },
          ],
        },
        {
          titulo: "Registro Narrativo",
          descricao: "Descreva com suas palavras como foi a aula.",
          perguntas: [
            {
              id: "resumo_aula",
              tipo: "texto_longo",
              label: "Resumo da aula",
              descricao: "O que foi abordado? Como foi o desenvolvimento?",
              obrigatorio: true,
            },
            {
              id: "destaques",
              tipo: "texto_longo",
              label: "Destaques positivos",
              descricao: "O que funcionou bem? Alunos que se destacaram?",
              obrigatorio: false,
            },
            {
              id: "dificuldades",
              tipo: "texto_longo",
              label: "Dificuldades encontradas",
              descricao: "Houve algum problema no conteúdo, comportamento ou estrutura?",
              obrigatorio: false,
            },
            {
              id: "sugestoes",
              tipo: "texto_longo",
              label: "Sugestões e próximos passos",
              descricao: "O que pode ser melhorado? O que deve ser retomado na próxima aula?",
              obrigatorio: false,
            },
          ],
        },
      ],
    },
    isSystem: true,
  },
  {
    slug: "autoavaliacao_aluno",
    nome: "Autoavaliação do Aluno",
    descricao: "Avaliação rápida do aluno sobre a aula: clareza, dificuldade e comentários.",
    destinatario: "aluno",
    estrutura: {
      blocos: [
        {
          titulo: "Como foi a aula para você?",
          descricao: "Avalie sua experiência nesta aula.",
          perguntas: [
            {
              id: "clareza_aula",
              tipo: "escala_1_5",
              label: "Clareza do conteúdo",
              descricao: "O conteúdo foi apresentado de forma fácil de entender?",
              obrigatorio: true,
            },
            {
              id: "nivel_dificuldade",
              tipo: "escala_1_5",
              label: "Nível de dificuldade",
              descricao: "Como você avalia a dificuldade do que foi ensinado?",
              obrigatorio: true,
            },
            {
              id: "engajamento_pessoal",
              tipo: "escala_1_5",
              label: "Seu engajamento",
              descricao: "Quanto você se sentiu envolvido e participativo?",
              obrigatorio: false,
            },
          ],
        },
        {
          titulo: "Seu aprendizado",
          descricao: "Reflita sobre o que você aprendeu hoje.",
          perguntas: [
            {
              id: "aprendizado",
              tipo: "texto_longo",
              label: "O que você aprendeu hoje?",
              descricao: "Resumo do que ficou de mais importante para você.",
              obrigatorio: false,
            },
            {
              id: "duvidas",
              tipo: "texto_longo",
              label: "Ficou com alguma dúvida?",
              descricao: "Descreva o que não ficou claro ou o que gostaria de aprofundar.",
              obrigatorio: false,
            },
            {
              id: "comentario_livre",
              tipo: "texto_longo",
              label: "Comentário livre",
              descricao: "Qualquer outro feedback sobre a aula de hoje.",
              obrigatorio: false,
            },
          ],
        },
      ],
    },
    isSystem: true,
  },
];

// ====================================================================
// AVALIAÇÕES (relatórios de aula)
// ====================================================================
// Dados de teste para popular o relatório de Extrato de Horas.
// Cada avaliação vincula uma aula (agendamento) a um formulário de feedback.
export const SEED_AVALIACOES: AvaliacaoRecord[] = [];
