/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as CoordenacaoRouteImport } from './routes/coordenacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtividadesCursoIdRouteImport } from './routes/atividades.$cursoId'
import { Route as AtividadesRouteImport } from './routes/atividades.'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenacaoRoute = CoordenacaoRouteImport.update({
  id: '/coordenacao',
  path: '/coordenacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesCursoIdRoute = AtividadesCursoIdRouteImport.update({
  id: '/$cursoId',
  path: '/$cursoId',
  getParentRoute: () => AtividadesRoute,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtividadesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/atividades': typeof AtividadesRouteWithChildren
  '/auth': typeof AuthRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/cursos': typeof CursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atividades/': typeof AtividadesRoute
  '/atividades/$cursoId': typeof AtividadesCursoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/auth': typeof AuthRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/cursos': typeof CursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atividades': typeof AtividadesRoute
  '/atividades/$cursoId': typeof AtividadesCursoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/atividades': typeof AtividadesRouteWithChildren
  '/auth': typeof AuthRoute
  '/coordenacao': typeof CoordenacaoRoute
  '/cursos': typeof CursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atividades/': typeof AtividadesRoute
  '/atividades/$cursoId': typeof AtividadesCursoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/atividades'
    | '/auth'
    | '/coordenacao'
    | '/cursos'
    | '/reset-password'
    | '/atividades/'
    | '/atividades/$cursoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/auth'
    | '/coordenacao'
    | '/cursos'
    | '/reset-password'
    | '/atividades'
    | '/atividades/$cursoId'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/atividades'
    | '/auth'
    | '/coordenacao'
    | '/cursos'
    | '/reset-password'
    | '/atividades/'
    | '/atividades/$cursoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  AtividadesRoute: typeof AtividadesRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoordenacaoRoute: typeof CoordenacaoRoute
  CursosRoute: typeof CursosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenacao': {
      id: '/coordenacao'
      path: '/coordenacao'
      fullPath: '/coordenacao'
      preLoaderRoute: typeof CoordenacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/$cursoId': {
      id: '/atividades/$cursoId'
      path: '/$cursoId'
      fullPath: '/atividades/$cursoId'
      preLoaderRoute: typeof AtividadesCursoIdRouteImport
      parentRoute: typeof AtividadesRoute
    }
    '/atividades/': {
      id: '/atividades/'
      path: '/'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof AtividadesRoute
    }
  }
}

interface AtividadesRouteChildren {
  AtividadesRoute: typeof AtividadesRoute
  AtividadesCursoIdRoute: typeof AtividadesCursoIdRoute
}

const AtividadesRouteChildren: AtividadesRouteChildren = {
  AtividadesRoute: AtividadesRoute,
  AtividadesCursoIdRoute: AtividadesCursoIdRoute,
}

const AtividadesRouteWithChildren = AtividadesRoute._addFileChildren(
  AtividadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  AtividadesRoute: AtividadesRouteWithChildren,
  AuthRoute: AuthRoute,
  CoordenacaoRoute: CoordenacaoRoute,
  CursosRoute: CursosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
